Move ask_password and get_session_key to lib-bwmenu

diff --git a/scripts/lib-bwmenu b/scripts/lib-bwmenu
--- a/scripts/lib-bwmenu
+++ b/scripts/lib-bwmenu
@@ -1,6 +1,29 @@
 #!/bin/bash
 # Helper functions
 
+ask_password() {
+  mpw=$(rofi -dmenu -p "Master Password" -password -lines 0) || exit $?
+  echo "$mpw" | bw unlock 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/' || exit_error $? "Could not unlock vault"
+}
+
+get_session_key() {
+  if [ $AUTO_LOCK -eq 0 ]; then
+    keyctl purge user bw_session &>/dev/null
+    BW_HASH=$(ask_password)
+  else
+    if ! key_id=$(keyctl request user bw_session 2>/dev/null); then
+      session=$(ask_password)
+      [[ -z "$session" ]] && exit_error 1 "Could not unlock vault"
+      key_id=$(echo "$session" | keyctl padd user bw_session @u)
+    fi
+    
+    if [ $AUTO_LOCK -gt 0 ]; then
+      keyctl timeout "$key_id" $AUTO_LOCK
+    fi
+    BW_HASH=$(keyctl pipe "$key_id")
+  fi
+}
+
 # Extract item or items matching .name, including deduplication
 # $1: item name, prepended or not with deduplication mark
 array_from_name() {
